// import Font Awesome CSS
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

import './globals.css'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import Nav from '@/Components/Nav'
import { ThemeProvider } from "@/contexts/ThemeContext";
import { ViewsCountProvider } from "@/contexts/ViewsCount";


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ViewsCountProvider>
            <ThemeProvider>
              <Nav />
              {children}
            </ThemeProvider>
          </ViewsCountProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
